version: "3.9"

services:
  laravelapp:
    container_name: laravel-11
    build: .
    restart: always
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - laravel
  # db:
  #   container_name: db
  #   image: postgres:12
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  mysql:
      image: mysql:8.0
      restart: always
      ports:
          - "3308:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
          # - MYSQL_DATABASE=${DB_DATABASE}
          # - MYSQL_USER=${DB_USERNAME}
          # - MYSQL_PASSWORD=${DB_PASSWORD}
          # - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

          - MYSQL_DATABASE=myDb
          - MYSQL_USER=user
          - MYSQL_PASSWORD=test
          - MYSQL_ROOT_PASSWORD=test
            
      volumes:
          - ./dump:/docker-entrypoint-initdb.d
          - ./conf:/etc/mysql/conf.d
          - pgdata:/var/lib/mysql
      networks:
        - laravel

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 8081:80
      environment:
          - PMA_HOST=mysql
      networks:
        - laravel
      
volumes:
  pgdata: {}
    
networks:
  laravel: